CREATE TABLE IF NOT EXISTS reminders(
  id INT AUTO_INCREMENT PRIMARY KEY,
  habit_id INT NOT NULL,
  reminder_time TIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (habit_id) REFERENCES habits(id) ON DELETE CASCADE
);
